### PR TITLE
Remove sync constraints

### PR DESCRIPTION
**Pull request by stefanprodan**
## Description

Remove comparison between the `.spec` fields so that resources can be re-synced. The diff constraint is no longer needed since we use an annotation to prevent the mounts from being overwritten.

Do not re-apply `resourceVersion` on function update to allow resources to be re-synced.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Fix: #95
Fix: #89

## How Has This Been Tested?

- [ ] I have run the [certifier](https://github.com/openfaas/certifier)

Tested on EKS 1.14 by applying the nodeinfo function with and without changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Impact to existing users

No impact to current users.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by stefanprodan** [comment]
This depends on #104 Once the go mod changes are merged into master I'll rebase this PR.

**Comment by alexellis** [comment]
The dependent PR has been merged.

**Comment by alexellis** [comment]
You should be able to make the changes you wanted now @stefanprodan

**Comment by stefanprodan** [comment]
@alexellis this is ready for merge now

**Comment by alexellis** [comment]
Merged into master, with a new release cut.

**Pull request merged**
