### PR TITLE
 Fix ClusterIP creation race condition and other improvements

### PR DESCRIPTION
**Pull request by stefanprodan**
This PR does the following:

* fix ClusterIP creation race condition when multiple operator instances are running
* improve logging (deployment update errors, service creation errors)
* set deployment strategy to max unavailable 0 (ensure no downtime during a rolling update)
* update the gateway and operator versions in the deploy manifests
* update readme to reflect the secrets path change

All changes have been tested on GKE 1.10

### CODE REVIEW

**Comment by affix** [comment]
LGTM

**Comment by alexellis** [comment]
How have you tested the issue is fixed? Can you give some details please Stefan? I'll also look at bringing over the GitHub pr template

**Comment by affix** [comment]
@alexellis I'll give it a test on my Cluster tonight make sure everything works as expected, From reading the code looks like it will work and I trust @stefanprodan has tested it on GKE

**Comment by stefanprodan** [comment]
I was running 4 instances of the operator and noticed the race condition. I fixed it and tested with several function all over again.

**Comment by affix** [comment]
@stefanprodan Was it 4 instances in the same NS?

**Comment by stefanprodan** [comment]
@affix I did scale up the Gateway deployment to 4 replicas and since the operator runs as a sidecar it got to 4 instances as well.

**Comment by stefanprodan** [comment]
Here is the test project with my own build https://github.com/stefanprodan/openfaas-flux/blob/master/releases/openfaas.yaml#L30

**Comment by affix** [comment]
awesome @stefanprodan I will do some testing on it tonight (first attempt to replicate it)

**Comment by alexellis** [comment]
Actually I just saw that you put 
> All changes have been tested on GKE 1.10

I don't want this constructive feedback to draw away from the good work you are doing, so I'll try to explain why I am asking for this.

The PR covers 5 commits but they don't contain details on **how they were tested**. We need to record that either in the PR or the commits (ideally both)

Why is this important? We need the commits to make sense to the rest of the community and anyone who has to work on the code in the future. 

The commit messages could also be a bit more verbose:

> improve logging (deployment update errors, service creation errors)

Which error(s)? Improve how?

**Pull request merged**
