### PR TITLE
Fixed validation of resources

### PR DESCRIPTION
**Pull request by bartsmykla**
Added omitempty to FunctionResources (Memory and CPU)

Fixes: https://github.com/openfaas-incubator/openfaas-operator/issues/54

Signed-off-by: Bart Smykla <bsmykla@vmware.com>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
- I deployed a function without limits
- I deployed a function with only CPU limit
- I deployed a function with only memory limit
- I deployed a function with both CPU and memory limits

- [x] I have run the [certifier](https://github.com/openfaas/certifier)
Results:
```
=== RUN   Test_Access_Secret
=== RUN   Test_Access_Secret/Empty_QueryString
--- PASS: Test_Access_Secret (27.81s)
    --- PASS: Test_Access_Secret/Empty_QueryString (27.51s)
        verify.go:71: [1/30] Got correct response: 200 - https://gateway/function/test-secret
=== RUN   Test_Deploy_Stronghash
--- PASS: Test_Deploy_Stronghash (0.39s)
=== RUN   Test_Deploy_PassingCustomEnvVars_AndQueryString
=== RUN   Test_Deploy_PassingCustomEnvVars_AndQueryString/Empty_QueryString
=== RUN   Test_Deploy_PassingCustomEnvVars_AndQueryString/Populated_QueryString
--- PASS: Test_Deploy_PassingCustomEnvVars_AndQueryString (62.59s)
    --- PASS: Test_Deploy_PassingCustomEnvVars_AndQueryString/Empty_QueryString (62.15s)
        verify.go:52: [1/30] Bad response want: [200], got: 504 - https://gateway/function/env-test
        verify.go:71: [2/30] Got correct response: 200 - https://gateway/function/env-test
    --- PASS: Test_Deploy_PassingCustomEnvVars_AndQueryString/Populated_QueryString (0.02s)
        verify.go:71: [1/30] Got correct response: 200 - https://gateway/function/env-test?testing=1
=== RUN   Test_Deploy_WithLabels
--- PASS: Test_Deploy_WithLabels (67.59s)
    verify.go:52: [1/30] Bad response want: [200], got: 504 - https://gateway/function/env-test-labels
    verify.go:71: [2/30] Got correct response: 200 - https://gateway/function/env-test-labels
=== RUN   Test_Deploy_WithAnnotations
--- PASS: Test_Deploy_WithAnnotations (76.26s)
    verify.go:52: [1/30] Bad response want: [200], got: 504 - https://gateway/function/env-test-annotations
    verify.go:71: [2/30] Got correct response: 200 - https://gateway/function/env-test-annotations
=== RUN   Test_InvokeNotFound
--- PASS: Test_InvokeNotFound (0.16s)
    verify.go:71: [1/30] Got correct response: 404 - https://gateway/function/notfound
=== RUN   Test_Invoke_With_Supported_Verbs
=== RUN   Test_Invoke_With_Supported_Verbs/GET
=== RUN   Test_Invoke_With_Supported_Verbs/POST
=== RUN   Test_Invoke_With_Supported_Verbs/PUT
=== RUN   Test_Invoke_With_Supported_Verbs/PATCH
=== RUN   Test_Invoke_With_Supported_Verbs/DELETE
--- PASS: Test_Invoke_With_Supported_Verbs (132.77s)
    --- PASS: Test_Invoke_With_Supported_Verbs/GET (131.58s)
        verify.go:71: [1/30] Got correct response: 200 - https://gateway/function/env-test-verbs
    --- PASS: Test_Invoke_With_Supported_Verbs/POST (0.65s)
        verify.go:71: [1/30] Got correct response: 200 - https://gateway/function/env-test-verbs
    --- PASS: Test_Invoke_With_Supported_Verbs/PUT (0.03s)
        verify.go:71: [1/30] Got correct response: 200 - https://gateway/function/env-test-verbs
    --- PASS: Test_Invoke_With_Supported_Verbs/PATCH (0.04s)
        verify.go:71: [1/30] Got correct response: 200 - https://gateway/function/env-test-verbs
    --- PASS: Test_Invoke_With_Supported_Verbs/DELETE (0.04s)
        verify.go:71: [1/30] Got correct response: 200 - https://gateway/function/env-test-verbs
PASS
ok  	github.com/openfaas/certifier/tests	367.582s
      368.61 real         0.75 user         0.59 sys
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Impact to existing users
I don't think that there is any impact, because in situation where there was only one of the limits it just didn't work, so I don't think that it affects current users

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @bartsmykla - thanks for working with Stefan on the fix for this. For testing can you run the certifier please which is now part of the template as requested by @ewilde.

One of the things I had feedback on from (on my own work with Git when joining VMware) was that I didn't always include how each commit was tested in the commit message. I think this would be a good practice for us to start across the community.

Could you update your commit description text with the testing you did like you have in the PR text? This will help us with `git blame` later on and any issues that may come up like the JSON serialization issue we had a few weeks back.

Cheers,

Alex

**Comment by bartsmykla** [comment]
@alexellis I think that it's a good idea. I'll run the certifier and include information about how I tested changes :-)

**Comment by bartsmykla** [comment]
@bartsmykla I have modified commit message and also run certifier. Can you check again?

**Comment by alexellis** [comment]
@bartsmykla thanks for the fix. Btw you pinged yourself in that last comment. 

@stefanprodan thanks for testing on GKE.

**Pull request merged**
