### PR TITLE
Prune the vendor folder

### PR DESCRIPTION
**Pull request by LucasRoesler**
**What**
- Add the prune unsued packages and tests to the go dep toml settings so
that the vendor folder only contains the required packages and
sub-packages

Signed-off-by: Lucas Roesler <roesler.lucas@gmail.com>

### CODE REVIEW

**Comment by stefanprodan** [comment]
Does the codegen works after this? You can test by running the scripts from `./hack`

**Comment by alexellis** [comment]
Good point.. Kubernetes can be a bit touch and go with too aggressive vendoring. If the codgen doesn't work, then I wonder if prune can apply to a single dependency for this case @LucasRoesler ?

@stefanprodan how long does codegen take - could we run it as a CI/validation task? 

Alex

**Comment by stefanprodan** [comment]
It runs instantly

**Comment by stefanprodan** [comment]
I’m asking Luke if he tested the codegen because I did try purging the vendor before and it didn’t work

**Comment by LucasRoesler** [comment]
No it does not work now

**Comment by LucasRoesler** [comment]
But there are some other tweaks to the Gopkg that we can make to fix it

**Comment by alexellis** [comment]
Looks like we are ready to merge this now?

**Pull request merged**
