### PR TITLE
Create unit test to verify spec annotation

### PR DESCRIPTION
**Pull request by LucasRoesler**
- Add unit test to ensure that makeAnnotations method is idempotent and
that it does not modify the original function specification

## Motivation and Context

- ~I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))~
- This validates the error behavior of the regression introduced in version 0.8.8
- We discussed creating this test during the contributors meeting
- The test will fail in the current branch because it is based on the 0.8.8 tag, but passes when based on master. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by LucasRoesler** [comment]
@stefanprodan here is that unit test we discussed during the contributor meeting.

**Comment by stefanprodan** [comment]
@LucasRoesler I've added some tests in https://github.com/openfaas-incubator/openfaas-operator/blob/master/pkg/controller/annotations_test.go your test should be added to this file I think.

**Comment by LucasRoesler** [comment]
Makes sense.  I didn't see that file because I created the test on SHA from the 0.8.8 tag

**Comment by LucasRoesler** [comment]
Done, rebased and moved it to master. 

Per the conversation in the contrib meeting, this test does fail on the 0.8.8 tag and confirms the suspicion that using the pointer allowed the original spec to be modified and caused a loop.

**Comment by alexellis** [comment]
Put it on the merge queue if ready.

**Comment by alexellis** [comment]
Thanks for this 🌮

**Pull request merged**
